import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const rootDir = dirname(fileURLToPath(import.meta.url));
const prod = process.argv[2] === 'production';
const runtimeDir = process.env.VAULT_PLUGIN_DIR
	? resolve(process.env.VAULT_PLUGIN_DIR)
	: rootDir;
const outfile = resolve(runtimeDir, 'main.js');

mkdirSync(dirname(outfile), { recursive: true });

const context = await esbuild.context({
	banner: { js: banner },
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile,
	minify: prod,
});

if (prod) {
	await context.rebuild();
	for (const file of ['manifest.json', 'styles.css']) {
		copyFileSync(resolve(rootDir, file), resolve(runtimeDir, file));
	}
	process.exit(0);
} else {
	await context.watch();
}